apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook-go
  template:
    metadata:
      labels:
        app: guestbook-go
    spec:
      containers:
      - name: guestbook-go
        image: saumyasrivastava2001/guestbook-go:latest
        securityContext:
          privileged: true
        ports:
        - containerPort: 3000
